apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notes.fullname" . }}-config
  labels:
    {{- include "notes.labels" . | nindent 4 }}
data:
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}
  NOTES_DATA_PATH: /data/notes.json
