apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting-app
  labels:
    app: troubleshooting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: troubleshooting-app
  template:
    metadata:
      labels:
        app: troubleshooting-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
