apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  namespace: devops-homework
spec:
  type: NodePort
  selector:
    app: service-web
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30081
