apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-failed
  namespace: devops-homework
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo intentional-failure; exit 1
