apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-startup
  namespace: devops-homework
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sh
    - -c
    - sleep 20; touch /tmp/started; sleep 3600
    startupProbe:
      exec:
        command:
        - test
        - -f
        - /tmp/started
      periodSeconds: 3
      failureThreshold: 15
    livenessProbe:
      exec:
        command:
        - test
        - -f
        - /tmp/started
      periodSeconds: 3
