apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-init
  namespace: devops-homework
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sh
    - -c
    - cat /shared/message; sleep 3600
    volumeMounts:
    - name: shared
      mountPath: /shared
  volumes:
  - name: shared
    emptyDir: {}
  initContainers:
  - name: setup
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo init-complete > /shared/message
    volumeMounts:
    - name: shared
      mountPath: /shared
