apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-multi
  namespace: devops-homework
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo app-started; sleep 3600
  - name: sidecar
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo sidecar-started; sleep 3600
