apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-data
  namespace: notes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
